'use strict';
const icons = {
  messages:'M3 3h18v13H9l-6 5Z M7 7h10 M7 11h7',
  folders:'M3 7h7l2 2h9v11H3Z M3 7V4h7l2 3h8v2',
  home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',
  work:'M8 4H5a2 2 0 0 0-2 2v14h18V6a2 2 0 0 0-2-2h-3 M8 3h8v4H8Z M7 12l2 2 4-4 M7 18h10',
  projects:'M3 7h7l2 2h9v11H3Z M3 7V4h7l2 3h8v2',
  mail:'M3 5h18v14H3Z M3 6l9 7 9-7',
  apps:'M3 3h7v7H3Z M14 3h7v7h-7Z M3 14h7v7H3Z M14 14h7v7h-7Z',
  admin:'M12 3 3 7v5c0 5 9 9 9 9s9-4 9-9V7Z M8 12l3 3 5-6',
  search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',
  bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5Z M10 21h4 M12 2v2',
  calendar:'M3 5h18v16H3Z M7 3v4 M17 3v4 M3 10h18 M7 14h2 M14 14h2 M7 18h2',
  arrow:'M5 12h14 M14 7l5 5-5 5',
  clock:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0 M12 6v6l4 2',
  alert:'M12 3 2 21h20Z M12 9v5 M12 17v1',
  close:'M6 6l12 12 M6 18 18 6',
  cube:'M12 2 2 7v10l10 5 10-5V7Z M2 7l10 5 10-5 M12 12v10 M7 4l10 5',
  device:'M2 3h20v14H2Z M8 21h8 M12 17v4',
  truck:'M1 5h13v12H1Z M14 9h5l4 5v3h-9 M7 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0 M21 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0',
  chart:'M4 3v18h18 M8 16v-5 M13 16V7 M18 16V4',
  plus:'M12 5v14 M5 12h14',
  file:'M5 2h9l5 5v15H5Z M14 2v6h5 M9 13h6 M9 17h6',
  check:'M5 12l4 4L19 6',
};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name] || icons.apps}"/></svg>`;
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav = [['home','Home','home'],['work','My Work','work'],['projects','Projects','projects'],['mail','Mail','mail'],['messages','Messages','messages'],['folders','Folder Links','folders'],['apps','App Catalogue','apps'],['admin','Admin','admin']];
const tasks = [
  {id:1,title:'Review cold plate validation results',project:'Atlas · Cold plate programme',due:'Today',priority:'High priority',status:'In progress',owner:'Richard',detail:'Review the thermal performance summary from the latest validation run. Confirm the acceptance criteria and capture any follow-up work before Monday’s engineering review.'},
  {id:2,title:'Approve manifold drawing pack',project:'Orion · Manifold assembly',due:'Today',priority:'High priority',status:'To do',owner:'Richard',detail:'Check revision C of the manifold drawing pack against the agreed interface dimensions. The manufacturing team is waiting for an internal review decision.'},
  {id:3,title:'Send updated project milestones',project:'Meridian · Rack integration',due:'Mon',priority:'Normal',status:'To do',owner:'Richard',detail:'Review the revised integration sequence and prepare the milestone summary for the project team. This prototype can record completion only; it does not send messages.'},
  {id:4,title:'Review supplier lead-time options',project:'Orion · Manifold assembly',due:'Tue',priority:'Normal',status:'Waiting',owner:'Richard',detail:'Compare the two sample machining schedules once supplier feedback is available. Keep the prototype task in Waiting until the review is ready.'},
  {id:5,title:'Check September capacity plan',project:'Operations · Weekly planning',due:'Wed',priority:'Normal',status:'To do',owner:'Richard',detail:'Review engineering and operations capacity for next week and identify unallocated work.'},
];
const projects = [
  {id:1,name:'Atlas',subtitle:'Cold plate programme',status:'On track',progress:72,owner:'Sarah Murphy',initials:'SM',date:'25 Sep',detail:'Thermal validation is underway. Current results meet the working performance envelope, with the final review planned for Monday.',milestone:'Validation sign-off',next:'Review test results and freeze the validation report.'},
  {id:2,name:'Orion',subtitle:'Manifold assembly',status:'At risk',progress:48,owner:'James Kelly',initials:'JK',date:'21 Sep',detail:'A supplier lead-time change may affect the machining slot. Drawing approval is needed before an alternative schedule can be confirmed.',milestone:'Manufacturing release',next:'Approve drawing pack and review supplier options.'},
  {id:3,name:'Meridian',subtitle:'Rack integration',status:'On track',progress:85,owner:'Richard',initials:'RM',date:'30 Sep',detail:'The integration plan is nearly complete. The team is preparing the handover checklist and coordinating final assembly.',milestone:'Integration handover',next:'Confirm updated milestones with the project team.'},
];
const mails = [
  {id:1,initials:'SM',sender:'Sarah Murphy',role:'Engineering',time:'10:42',subject:'Atlas validation — ready for your review',excerpt:'Latest thermal results and the summary are attached.',tag:'Review needed',project:'Atlas',attachment:'Atlas_validation_summary.pdf',body:'Hi Richard,\n\nThe latest validation results are ready for review. The test points are within the agreed envelope, and I have highlighted two items for discussion in the summary.\n\nCould you look through these ahead of Monday’s engineering review?\n\nThanks,\nSarah'},
  {id:2,initials:'JK',sender:'James Kelly',role:'Project delivery',time:'09:18',subject:'Orion — supplier lead-time update',excerpt:'We have two options for the machining slot.',tag:'Action needed',project:'Orion',attachment:'Orion_schedule_options.pdf',body:'Hi Richard,\n\nThe supplier has moved the original machining slot. We have two possible alternatives, but both depend on approving the drawing pack first.\n\nI have attached the schedule options. Please review the drawing pack so we can agree the next step on Monday.\n\nThanks,\nJames'},
  {id:3,initials:'AC',sender:'Aoife Collins',role:'Operations',time:'Yesterday',subject:'Next week’s capacity plan',excerpt:'A quick check on engineering availability for next week.',tag:'For review',project:'Operations',attachment:null,body:'Hi Richard,\n\nThe draft capacity plan for next week is ready. There is some space available on Wednesday if we need to bring the integration review forward.\n\nPlease take a look when you get a chance.\n\nThanks,\nAoife'},
];
const apps = [
  {id:1,name:'Mail',category:'Productivity',icon:'mail',status:'Installed',version:'2.8.1',description:'Triage correspondence, follow up on decisions, and keep project conversations together.',screen:'mail'},
  {id:2,name:'Calendar',category:'Productivity',icon:'calendar',status:'Installed',version:'3.2.0',description:'Plan your week, balance capacity, and keep upcoming commitments in view.',screen:'calendar'},
  {id:3,name:'Projects',category:'Delivery',icon:'projects',status:'Installed',version:'1.9.3',description:'Track project milestones, ownership, and the work that keeps delivery moving.',screen:'projects'},
  {id:4,name:'PLM',category:'Engineering',icon:'cube',status:'Available',version:'1.4.0',description:'Explore product structures, controlled drawings, and engineering changes.'},
  {id:5,name:'Shipping',category:'Operations',icon:'truck',status:'Available',version:'2.1.2',description:'Prepare shipments and coordinate the movement of parts and equipment.'},
  {id:6,name:'Asset Tracker',category:'Operations',icon:'device',status:'Installed',version:'1.6.2',description:'Keep equipment, assigned devices, and service history organised.'},
  {id:7,name:'ProcFlow',category:'Operations',icon:'work',status:'Restricted',version:'1.2.0',description:'Manage purchasing workflows, supplier reviews, and approval checkpoints.'},
  {id:8,name:'Budget',category:'Finance',icon:'chart',status:'Restricted',version:'1.1.0',description:'Review budgets, spending commitments, and financial planning.'},
];
const users = [
  {id:1,name:'Richard',initials:'RM',team:'Leadership',role:'Administrator',apps:8,device:'NX-DESKTOP-01',status:'Active'},
  {id:2,name:'Sarah Murphy',initials:'SM',team:'Engineering',role:'Engineer',apps:5,device:'NX-LAPTOP-04',status:'Active'},
  {id:3,name:'James Kelly',initials:'JK',team:'Delivery',role:'Project Manager',apps:4,device:'NX-LAPTOP-07',status:'Active'},
  {id:4,name:'Aoife Collins',initials:'AC',team:'Operations',role:'Operations',apps:6,device:'NX-DESKTOP-03',status:'Active'},
  {id:5,name:'Daniel Walsh',initials:'DW',team:'Engineering',role:'Engineer',apps:5,device:'Not assigned',status:'Invited'},
];
const state = {page:'home',workFilter:'Open',projectFilter:'All projects',appFilter:'All apps',appQuery:'',adminTab:'Users',mailId:1,mailFilter:'Needs attention',done:new Set(),reviewed:new Set(),requests:new Set(),dismissed:false};
const main = document.querySelector('#main');
const overlay = document.querySelector('#overlay');
let lastFocus, toastTimer;
const tone = status => ({'On track':'green','Active':'green','Installed':'green','Available':'blue','Restricted':'purple','At risk':'amber','Invited':'amber','High priority':'amber','Normal':'blue','Review needed':'blue','Action needed':'amber','For review':'blue','Stable':'green','Pilot':'blue','Draft':'purple','Current':'green','Update available':'amber'}[status] || 'blue');
const pill = status => `<span class="pill ${tone(status)}">${esc(status)}</span>`;
const link = (text,action,id='') => `<button class="link-button" data-action="${action}" data-id="${id}">${text} ${icon('arrow')}</button>`;
const button = (text,action,id='',primary=false,ico='') => `<button class="button ${primary?'primary':''}" data-action="${action}" data-id="${id}">${ico?icon(ico):''}${text}</button>`;
function heading(eyebrow,title,subtitle,actions=''){return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="heading-actions">${actions}</div></div>`;}
function panel(title,body,action='',extra=''){return `<section class="panel"><div class="panel-header"><h2>${title}</h2>${action}</div>${extra}${body}</section>`;}
function tabs(items,current,type){return `<div class="tabs" aria-label="${type} filters">${items.map(x=>`<button data-action="filter" data-type="${type}" data-id="${x}" class="${x===current?'active':''}" aria-pressed="${x===current}">${x}</button>`).join('')}</div>`;}
function taskRow(t){const done=state.done.has(t.id);return `<div class="task-row ${done?'done':''}"><button class="check" data-action="complete" data-id="${t.id}" aria-label="${done?'Reopen':'Complete'} ${esc(t.title)}" aria-pressed="${done}">${done?'✓':''}</button><div class="task-body"><button class="task-title" data-action="task" data-id="${t.id}">${t.title}</button><div class="task-meta"><span>${t.project}</span><i></i><span>${done?'Completed':t.status}</span></div></div>${pill(t.priority)}<span class="task-due">${t.due}</span></div>`;}
function mailRow(m,select=false){return `<div class="mail-row ${select&&state.mailId===m.id?'selected':''}" role="button" tabindex="0" data-action="mail" data-id="${m.id}" aria-label="Read ${esc(m.subject)}"><span class="avatar">${m.initials}</span><div class="mail-copy"><div class="mail-person">${m.sender}<time>${m.time}</time></div><div class="mail-subject">${m.subject}</div>${select?`<p class="mail-excerpt">${m.excerpt}</p>`:''}${pill(state.reviewed.has(m.id)?'Reviewed':m.tag)}</div></div>`;}
function projectTable(){return `<table class="project-table"><thead><tr><th>PROJECT</th><th>STATUS</th><th>PROGRESS</th><th>NEXT MILESTONE</th></tr></thead><tbody>${projects.map(p=>`<tr><td><button class="project-name" data-action="project" data-id="${p.id}">${p.name}</button><small>${p.subtitle}</small></td><td>${pill(p.status)}</td><td><span class="progress-label">${p.progress}%</span><div class="progress ${p.status==='At risk'?'amber':''}"><i style="width:${p.progress}%"></i></div></td><td>${p.date}<small>${p.milestone}</small></td></tr>`).join('')}</tbody></table>`;}
function schedule(){return `<p class="schedule-date">MONDAY, 14 SEPTEMBER</p><div class="event"><div class="event-time">09:30<small>30 min</small></div><div class="event-detail"><h3>Engineering review</h3><small>Atlas · Meeting room 1</small></div></div><div class="event"><div class="event-time">11:00<small>45 min</small></div><div class="event-detail"><h3>Orion supplier catch-up</h3><small>Orion · Teams meeting</small></div></div><div class="event"><div class="event-time">14:00<small>30 min</small></div><div class="event-detail"><h3>Weekly capacity planning</h3><small>Operations · Meeting room 1</small></div></div><div class="panel-foot">All times Europe/Dublin<span>3 upcoming events</span></div>`;}
function home(){const open=tasks.filter(t=>!state.done.has(t.id));return heading('SATURDAY, 12 SEPTEMBER 2026','Good morning, Richard.','A clear view of your work, your projects, and what needs attention.',button('View my work','go','work',true,'work'))+
  `${hubQuickAccess()}<div class="stats">${[
    ['work','Your open work',open.length,'assigned to you',`${open.filter(t=>t.due==='Today').length} priorities for today`,'orange-text','work'],
    ['projects','Active projects','3','in delivery','2 on track · 1 needs attention','','projects'],
    ['mail','Mail needing attention',mails.length-state.reviewed.size,'conversations','Reviews and decisions waiting','','mail'],
    ['calendar','Next on your calendar','09:30','Monday','Engineering review · Atlas','green-text','calendar'],
  ].map(([ic,label,value,suffix,note,cls,target])=>`<button class="stat" data-action="${target==='calendar'?'calendar':'go'}" data-id="${target}"><div class="stat-top">${label}${icon(ic)}</div><div class="stat-value">${value}<span>${suffix}</span></div><small class="${cls}">${note}</small></button>`).join('')}</div>`+
  `<div class="dashboard-grid"><div class="column">${panel(`Your priorities <span class="badge-number">${open.length}</span>`,open.slice(0,3).map(taskRow).join('')+`<div class="panel-foot">Start with the decisions that unblock others.${link('All work','go','work')}</div>`,'','<p class="focus-label">FOCUS FOR TODAY</p>')}${panel('Project health',projectTable(),link('All projects','go','projects'))}${panel(`Mail needing attention <span class="badge-number">${mails.length-state.reviewed.size}</span>`,mails.filter(m=>!state.reviewed.has(m.id)).map(m=>mailRow(m)).join('')||'<p class="empty">You’re all caught up.</p>',link('View mail','go','mail'))}</div><div class="column">${panel('Coming up',schedule(),link('Calendar','calendar'))}${panel('Heads up',state.dismissed?'<p class="panel-description">No new alerts. You’re up to date.</p>':`<div class="alert">${icon('alert')}<div><h3>Orion milestone needs attention</h3><p>Supplier lead time may affect the manufacturing release on 21 Sep.</p>${link('Review project','project',2)}</div></div>`)}${panel('Recent activity',`<div class="activity"><span class="activity-dot"></span><div><p><b>Sarah</b> added the Atlas validation report.</p><small>Today, 10:42 · Atlas</small></div></div><div class="activity"><span class="activity-dot"></span><div><p><b>James</b> updated a project milestone.</p><small>Today, 09:10 · Orion</small></div></div><div class="activity"><span class="activity-dot"></span><div><p><b>You</b> reviewed the integration checklist.</p><small>Yesterday, 16:20 · Meridian</small></div></div>`)}<div class="app-shortcuts">${['mail','calendar','projects','apps'].map((a,i)=>`<button class="shortcut" data-action="${a==='calendar'?'calendar':'go'}" data-id="${a}">${icon(a)}${['Mail','Calendar','Projects','All apps'][i]}</button>`).join('')}</div></div></div>`;}
function work(){let filtered=tasks.filter(t=>state.workFilter==='Completed'?state.done.has(t.id):!state.done.has(t.id)&&(state.workFilter!=='Due today'||t.due==='Today')&&(state.workFilter!=='Waiting'||t.status==='Waiting'));return heading('PERSONAL WORKSPACE','My Work','Your commitments, organised around the next useful step.')+`<div class="toolbar">${tabs(['Open','Due today','Waiting','Completed'],state.workFilter,'work')}<small>${filtered.length} tasks · Assigned to Richard</small></div>`+panel('Your work',filtered.map(taskRow).join('')||'<p class="empty">No tasks in this view.</p>');}
function projectPage(){let filtered=projects.filter(p=>state.projectFilter==='All projects'||p.status===state.projectFilter);return heading('DELIVERY OVERVIEW','Projects','Milestones, progress, and the decisions that keep delivery moving.')+`<div class="toolbar">${tabs(['All projects','On track','At risk'],state.projectFilter,'projects')}<small>3 active projects · September 2026</small></div><div class="cards">${filtered.map(p=>`<article class="panel project-card"><div class="card-top"><span class="app-icon">${icon('projects')}</span>${pill(p.status)}</div><h2>${p.name} <small>${p.subtitle}</small></h2><p>${p.detail}</p><div class="progress-label"><span>Project progress</span><b>${p.progress}%</b></div><div class="progress ${p.status==='At risk'?'amber':''}"><i style="width:${p.progress}%"></i></div><div class="card-bottom"><div><small>${p.milestone}</small><b style="font-size:12px">${p.date} 2026</b></div>${link('View project','project',p.id)}</div></article>`).join('')}</div>`;}
function mailPage(){const visible=mails.filter(m=>state.mailFilter==='All mail'||!state.reviewed.has(m.id));if(!visible.some(m=>m.id===state.mailId))state.mailId=visible[0]?.id;const m=visible.find(m=>m.id===state.mailId);return heading('COMMUNICATIONS','Mail','The conversations that need your attention, with project context close by.')+`<div class="toolbar">${tabs(['Needs attention','All mail'],state.mailFilter,'mail')}<small>${visible.length} sample conversations</small></div><section class="panel mail-layout"><div class="mail-list">${visible.map(m=>mailRow(m,true)).join('')||'<p class="empty">All caught up.</p>'}</div><article class="mail-reader">${m?`${pill(m.tag)}<h2>${m.subject}</h2><div class="sender"><span class="avatar">${m.initials}</span><div><b>${m.sender}</b><small>${m.role} · To Richard · ${m.time}</small></div></div><div class="message">${esc(m.body)}</div>${m.attachment?`<button class="attachment" data-action="attachment" data-id="${m.id}">${icon('file')} ${m.attachment}</button>`:''}<div class="heading-actions">${button(state.reviewed.has(m.id)?'Mark as needing attention':'Mark reviewed','review-mail',m.id,true,'check')}${button('Create follow-up','follow-up',m.id,false,'plus')}${link('Project context','mail-project',m.id)}</div><p class="prototype-caption">Sample correspondence for layout review.</p>`:'<p class="empty">No conversations need attention.</p>'}</article></section>`;}
function appPage(){const filtered=apps.filter(a=>(state.appFilter==='All apps'||a.status===state.appFilter)&&(a.name+' '+a.category).toLowerCase().includes(state.appQuery.toLowerCase()));return heading('YOUR NEXALUS TOOLKIT','App Catalogue','Find the right tool for the job. See what’s installed and what’s available to your team.')+`<div class="toolbar">${tabs(['All apps','Installed','Available','Restricted'],state.appFilter,'apps')}<input class="input" id="app-search" placeholder="Search apps…" aria-label="Search apps" value="${esc(state.appQuery)}"></div><div class="cards">${filtered.map(a=>`<article class="panel app-card"><div class="card-top"><span class="app-icon">${icon(a.icon)}</span>${pill(a.status)}</div><h2>${a.name}</h2><small>${a.category}</small><p>${a.description}</p><div class="card-bottom"><small>Version ${a.version}<br>${a.status==='Installed'?'On this device':a.status==='Restricted'?'Role approval required':'Ready to explore'}</small>${button(a.status==='Installed'?'Preview app':a.status==='Available'?'View app':'View access','app',a.id,false,a.status==='Restricted'?'admin':'arrow')}</div></article>`).join('')||'<p class="empty">No apps match your search.</p>'}</div><p class="prototype-caption">Availability and versions are illustrative. All catalogue actions are local previews.</p>`;}
function table(headers,rows){return `<div class="panel"><table class="wide-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function adminPage(){let body='';switch(state.adminTab){
  case 'Users':body=table(['User','Role','App access','Status',''],users.map(u=>[`<div class="table-person"><span class="avatar">${u.initials}</span><div><b>${u.name}</b><small>${u.team}</small></div></div>`,u.role,`${u.apps} apps`,pill(u.status),link('Manage','user',u.id)]));break;
  case 'Roles':body=table(['Role','Purpose','Members',''],[['Administrator','Workspace, access, and release management','1'],['Engineer','Engineering tools and project work','2'],['Project Manager','Milestones, delivery, and communications','1'],['Operations','Equipment, logistics, and purchasing','1']].map((r,i)=>[...r,link('Explore role','role',i)]));break;
  case 'App access':body=table(['Application','Access policy','Assigned roles',''],apps.map(a=>[`${icon(a.icon)} &nbsp; <b>${a.name}</b>`,pill(a.status==='Restricted'?'Restricted':'Available'),a.status==='Restricted'?'Administrator · Operations':a.category==='Engineering'?'Administrator · Engineer':'All workspace roles',link('Review policy','policy',a.id)]));break;
  case 'Devices':body=table(['Device','Assigned to','Platform','Health',''],users.slice(0,4).map((u,i)=>[`<b>${u.device}</b><small>Last seen ${i===2?'yesterday':'today'}</small>`,u.name,'Windows 11',pill(i===2?'Update available':'Current'),link('View device','device',u.id)]));break;
  case 'Versions':body=table(['Application','Stable version','Device coverage','Channel',''],apps.map((a,i)=>[a.name,a.version,`${i===1?'3 / 4':'4 / 4'} sample devices`,pill('Stable'),link('Version details','version',a.id)]));break;
  case 'Releases':body=table(['Release','Channel','Target audience','Status',''],[['Calendar 3.3.0','Pilot','Engineering · 2 devices','In review'],['Mail 2.8.1','Stable','All users · 4 devices','Published'],['PLM 1.5.0','Draft','Not assigned','Draft']].map((r,i)=>[r[0],pill(r[1]),r[2],r[3],link('Review release','release',i)]));break;
}return heading('WORKSPACE ADMINISTRATION','Admin','A single place to understand your team, app access, and desktop estate.')+`<div class="admin-banner">${icon('admin')}<div><b>Administrator preview</b><small>Explore representative controls. Edits apply only to this browser session.</small></div></div><div class="toolbar">${tabs(['Users','Roles','App access','Devices','Versions','Releases'],state.adminTab,'admin')}<small>Sample organisation</small></div>${body}`;}
function render(){document.querySelector('#breadcrumb').textContent=nav.find(n=>n[0]===state.page)?.[1]||'Home';document.querySelector('#navigation').innerHTML=nav.map(([id,label,ic])=>`<a href="#${id}" aria-label="${label}" class="${state.page===id?'active ':''}${id==='admin'?'admin-link':''}" ${state.page===id?'aria-current="page"':''}>${icon(ic)}${label}${id==='work'?`<span class="count">${tasks.length-state.done.size}</span>`:id==='mail'?`<span class="count">${mails.length-state.reviewed.size}</span>`:''}</a>`).join('');main.innerHTML=({home,work,projects:projectPage,mail:mailPage,apps:appPage,admin:adminPage,folders:folderPage,messages:messagesPage}[state.page]||home)();document.title=`${nav.find(n=>n[0]===state.page)?.[1]} · Nexalus Hub`;}
function go(page){if(location.hash===`#${page}`){state.page=page;render();}else location.hash=page;closeOverlay();}
function showToast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function showOverlay(content,search=false){lastFocus=document.activeElement;overlay.innerHTML=`<section class="${search?'search-modal':'drawer'}" role="dialog" aria-modal="true" aria-label="${search?'Search the Hub':'Detail preview'}"><div class="drawer-top"><span class="eyebrow">${search?'SEARCH WORKSPACE':'NEXALUS HUB · PREVIEW'}</span><button class="icon-button" data-action="close" aria-label="Close details">${icon('close')}</button></div>${content}</section>`;overlay.hidden=false;document.querySelector('.shell').inert=true;document.querySelector('.sidebar').inert=true;overlay.querySelector(search?'input':'button').focus();}
function closeOverlay(){if(overlay.hidden)return;overlay.hidden=true;overlay.innerHTML='';document.querySelector('.shell').inert=false;document.querySelector('.sidebar').inert=false;if(lastFocus?.isConnected)lastFocus.focus();else main.focus({preventScroll:true});}
function details(items){return `<div class="detail-grid">${items.map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')}</div>`;}
function taskDetail(id){const t=tasks.find(t=>t.id===id);showOverlay(`${pill(state.done.has(id)?'Completed':t.status)}<h2>${t.title}</h2><p>${t.detail}</p>${details([['Project',t.project],['Owner',t.owner],['Due',t.due],['Priority',t.priority]])}<div class="detail-section"><h3>Next step</h3><div class="timeline-line">Review the supporting information.<small>Then record the outcome for the team.</small></div></div>${button(state.done.has(id)?'Reopen task':'Mark complete','complete-detail',id,true,'check')}<p class="prototype-caption">Task changes are held in memory and reset on reload.</p>`);}
function projectDetail(id){const p=projects.find(p=>p.id===id);showOverlay(`${pill(p.status)}<h2>${p.name}</h2><p>${p.subtitle}</p><p>${p.detail}</p>${details([['Project lead',p.owner],['Next milestone',p.milestone],['Target date',p.date+' 2026'],['Progress',p.progress+'%']])}<h3>Next decision</h3><p>${p.next}</p><div class="detail-section"><h3>Milestone path</h3><div class="timeline-line">Requirements agreed ${pill('Complete')}</div><div class="timeline-line">${p.milestone} ${pill('In progress')}<small>${p.date} 2026</small></div><div class="timeline-line">Project handover<small>After milestone review</small></div></div>${button('View related work','project-work',id,true,'work')}`);}
function appDetail(id){const a=apps.find(a=>a.id===id);showOverlay(`<span class="app-icon">${icon(a.icon)}</span><h2>${a.name}</h2>${pill(a.status)}<p>${a.description}</p>${details([['Category',a.category],['Version',a.version],['Publisher','Nexalus Labs'],['Access',a.status==='Restricted'?'Approval required':'Workspace members']])}<h3>${a.status==='Installed'?'Ready in your workspace':a.status==='Available'?'Available to your team':'Access is managed by role'}</h3><p>${a.status==='Installed'?'Explore this app’s sample workspace in the Hub.':a.status==='Available'?'Preview how an installation request would appear.':'This role requires approval before the app would be available. You can preview an access request.'}</p>${button(a.status==='Installed'?'Explore app preview':state.requests.has(id)?'Request recorded in preview':a.status==='Available'?'Simulate install request':'Simulate access request',a.status==='Installed'?'app-preview':'app-request',id,true)}<p class="prototype-caption">No applications are launched, installed, or downloaded. Requests stay in this preview.</p>`);}
function userDetail(id){const u=users.find(u=>u.id===id);showOverlay(`<span class="avatar">${u.initials}</span><h2>${u.name}</h2>${pill(u.status)}${details([['Team',u.team],['Device',u.device],['App access',u.apps+' apps'],['Account type','Sample member']])}<label for="role-select">Role</label><select class="input" id="role-select">${['Administrator','Engineer','Project Manager','Operations'].map(r=>`<option ${r===u.role?'selected':''}>${r}</option>`).join('')}</select><p>Explore the role selector and save a sample assignment.</p>${button('Save preview role','save-role',id,true)}<p class="prototype-caption">This does not change real permissions or identities.</p>`);}
function searchResults(query=''){const list=[...nav.map(([id,label])=>({title:label,type:'Workspace',action:'go',id})),...projects.map(p=>({title:p.name+' · '+p.subtitle,type:'Project',action:'project',id:p.id})),...tasks.map(t=>({title:t.title,type:'Task',action:'task',id:t.id})),...apps.map(a=>({title:a.name,type:'App',action:'app',id:a.id})),...folderLinks.map(f=>({title:f.name,type:'Folder',action:'folder-detail',id:f.id})),...conversations.map(c=>({title:c.name,type:'Conversation',action:'conversation',id:c.id}))].filter(x=>x.title.toLowerCase().includes(query.toLowerCase()));document.querySelector('#search-results').innerHTML=list.map(x=>`<button class="search-result" data-action="${x.action}" data-id="${x.id}">${x.title}<small>${x.type}</small></button>`).join('')||'<p class="empty">No matching sample items.</p>';}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el)return;const action=el.dataset.action,id=Number(el.dataset.id);switch(action){
  case 'go':go(el.dataset.id);break;
  case 'close':closeOverlay();break;
  case 'filter':if(el.dataset.type==='folders')break;state[{work:'workFilter',projects:'projectFilter',apps:'appFilter',admin:'adminTab',mail:'mailFilter'}[el.dataset.type]]=el.dataset.id;render();break;
  case 'complete':state.done.has(id)?state.done.delete(id):state.done.add(id);render();showToast(state.done.has(id)?'Task completed in preview.':'Task reopened in preview.');break;
  case 'complete-detail':state.done.has(id)?state.done.delete(id):state.done.add(id);closeOverlay();render();showToast('Task updated in preview.');break;
  case 'task':taskDetail(id);break;
  case 'project':projectDetail(id);break;
  case 'project-work':state.workFilter='Open';go('work');showToast(`Showing your work, including ${projects.find(p=>p.id===id).name}.`);break;
  case 'mail':state.mailId=id;state.mailFilter=state.reviewed.has(id)?'All mail':state.mailFilter;go('mail');break;
  case 'review-mail':state.reviewed.has(id)?state.reviewed.delete(id):state.reviewed.add(id);render();showToast('Conversation updated in preview.');break;
  case 'follow-up':{const m=mails.find(m=>m.id===id);if(tasks.some(t=>t.mailId===id)){showToast('A follow-up already exists in My Work.');break;}tasks.push({id:tasks.length+1,title:`Follow up: ${m.subject}`,project:`${m.project} · Mail follow-up`,due:'Mon',priority:'Normal',status:'To do',owner:'Richard',detail:`Follow up with ${m.sender} about ${m.subject}. Created from the sample conversation.`,mailId:id});render();showToast('Follow-up added to My Work in this preview.');break;}
  case 'mail-project':{const m=mails.find(m=>m.id===id),p=projects.find(p=>p.name===m.project);if(p)projectDetail(p.id);else showOverlay('<h2>Operations planning</h2><p>This conversation relates to next week’s capacity plan.</p>'+button('View My Work','go','work',true));break;}
  case 'attachment':{const m=mails.find(m=>m.id===id);showOverlay(`${icon('file')}<h2>${m.attachment}</h2><p>Sample attachment summary</p>${details([['Project',m.project],['Shared by',m.sender]])}<p>${id===1?'The validation summary includes thermal test results, acceptance criteria, and two review points for the engineering meeting.':'Two machining schedule options are awaiting a drawing review before the manufacturing date can be confirmed.'}</p><p class="prototype-caption">This is an illustrative attachment preview; no document is downloaded.</p>`);break;}
  case 'calendar':showOverlay(`<h2>Coming up</h2><p>Your next working day at a glance.</p>${schedule()}<p class="prototype-caption">Sample appointments. No live calendar connection.</p>`);break;
  case 'alerts':showOverlay(`<h2>Workspace alerts</h2>${state.dismissed?'<p>No new alerts.</p>':`<p><b>Orion manufacturing release</b><br>Supplier lead time may affect the 21 Sep milestone.</p>${button('Review Orion','project',2,true)} ${button('Dismiss in preview','dismiss-alert')}`}<p class="prototype-caption">Alerts are illustrative.</p>`);break;
  case 'dismiss-alert':state.dismissed=true;closeOverlay();render();showToast('Alert dismissed in preview.');break;
  case 'app':appDetail(id);break;
  case 'app-request':state.requests.add(id);appDetail(id);showToast('Sample request recorded. No real request was sent.');break;
  case 'app-preview':{const a=apps.find(a=>a.id===id);if(a.screen==='calendar'){closeOverlay();showOverlay(`<h2>Calendar</h2>${schedule()}`);}else if(a.screen)go(a.screen);else showOverlay(`<h2>${a.name} preview</h2><p>Equipment and ownership at a glance.</p>${details([['Tracked assets','24'],['Assigned','21'],['Service due','2'],['Available','3']])}<h3>Recent equipment</h3><p>NX-LAPTOP-04 · Assigned to Sarah Murphy<br>Flow meter FM-012 · Calibration due 23 Sep<br>Test rig TR-002 · Engineering lab</p><p class="prototype-caption">Sample assets; no application is launched.</p>`);break;}
  case 'user':userDetail(id);break;
  case 'save-role':users.find(u=>u.id===id).role=document.querySelector('#role-select').value;closeOverlay();render();showToast('Role saved in preview only.');break;
  case 'role':{const roles=['Administrator','Engineer','Project Manager','Operations'];showOverlay(`<h2>${roles[id]}</h2><p>A representative role for ${['workspace configuration and governance','engineering delivery and controlled product data','project planning and communications','logistics, equipment, and purchasing'][id]}.</p>${details([['Sample members',users.filter(u=>u.role===roles[id]).length],['Scope','Company workspace']])}<h3>Representative access</h3><p>${['All applications · user management · release review','Mail · Calendar · Projects · PLM · Asset Tracker','Mail · Calendar · Projects · Asset Tracker','Mail · Calendar · Projects · Shipping · Asset Tracker · ProcFlow'][id]}</p><p class="prototype-caption">Role descriptions are illustrative; access is not enforced.</p>`);break;}
  case 'policy':{const a=apps.find(a=>a.id===id);showOverlay(`<h2>${a.name} access</h2>${pill(a.status==='Restricted'?'Restricted':'Available')}<p>Explore how app availability could be configured for the workspace.</p><label for="access-policy">Sample access policy</label><select class="input" id="access-policy"><option>Assigned roles only</option><option>All workspace members</option><option>Administrator approval required</option></select>${button('Preview policy','preview-policy',id,true)}<p class="prototype-caption">No real permissions are changed.</p>`);break;}
  case 'preview-policy':{const policy=document.querySelector('#access-policy').value;showOverlay(`<h2>Policy preview</h2><p><b>${apps.find(a=>a.id===id).name}</b></p>${details([['Proposed policy',esc(policy)],['Effect','Preview only']])}<p>This is how a policy summary would appear before a workspace change.</p>${button('Done','close','',true)}`);break;}
  case 'device':{const u=users.find(u=>u.id===id);showOverlay(`<h2>${u.device}</h2><p>Assigned to ${u.name}</p>${details([['Platform','Windows 11'],['Hub concept','01'],['Last seen',id===3?'Yesterday, 16:30':'Today, 09:12'],['Device health',id===3?'1 update available':'Current']])}<h3>Installed app versions</h3><p>Mail 2.8.1<br>Calendar ${id===3?'3.1.0':'3.2.0'}<br>Projects 1.9.3<br>Asset Tracker 1.6.2</p><p class="prototype-caption">Sample device inventory. No remote commands are available.</p>`);break;}
  case 'version':{const a=apps.find(a=>a.id===id);showOverlay(`<h2>${a.name} ${a.version}</h2>${pill('Stable')}<p>Representative version inventory for the workspace.</p>${details([['Publisher','Nexalus Labs'],['Release date','8 Sep 2026'],['Coverage',id===2?'3 of 4 sample devices':'4 of 4 sample devices'],['Channel','Stable']])}<h3>Release notes</h3><p>Improved navigation consistency, clearer status feedback, and small usability refinements.</p><p class="prototype-caption">All version numbers and coverage figures are sample data.</p>`);break;}
  case 'release':showOverlay(`<h2>${['Calendar 3.3.0','Mail 2.8.1','PLM 1.5.0'][id]}</h2>${pill(['Pilot','Stable','Draft'][id])}<p>${['A proposed pilot release for the engineering team.','A representative published release in the stable channel.','A draft release awaiting internal validation.'][id]}</p>${details([['Target',id===0?'Engineering':id===1?'All users':'Not assigned'],['Owner','Workspace administrator'],['Validation',id===2?'Pending':'Review complete'],['Rollout',id===0?'Pilot group':id===1?'Complete':'Not scheduled']])}<h3>Review checklist</h3><div class="timeline-line">Release notes prepared</div><div class="timeline-line">Sample device compatibility reviewed</div><div class="timeline-line">${id===2?'Validation still required':'Internal review complete'}</div>${button('Preview rollout summary','rollout',id,true)}<p class="prototype-caption">No releases are published or deployed from this prototype.</p>`);break;
  case 'rollout':showOverlay(`<h2>Rollout summary</h2><p>${['Calendar 3.3.0 would target 2 engineering devices in the pilot group.','Mail 2.8.1 is shown as published to 4 sample devices.','PLM 1.5.0 has no assigned audience. Validation would be required before scheduling.'][id]}</p>${pill('Preview only')}<p class="prototype-caption">No update was scheduled or deployed.</p>${button('Done','close','',true)}`);break;
  case 'search':showOverlay('<input class="input" id="global-search" aria-label="Search workspace" placeholder="Search tasks, projects, or apps…"><div id="search-results"></div>',true);searchResults();break;
}});
document.addEventListener('input',e=>{if(e.target.id==='global-search')searchResults(e.target.value);if(e.target.id==='app-search'){const caret=e.target.selectionStart;state.appQuery=e.target.value;render();const input=document.querySelector('#app-search');input.focus();input.setSelectionRange(caret,caret);}});
overlay.addEventListener('click',e=>{if(e.target===overlay)closeOverlay();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeOverlay();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('[data-action="search"]').click();return;}if(e.key==='Enter'&&e.target.matches('[role="button"]'))e.target.click();if(e.key===' '&&e.target.matches('[role="button"]')){e.preventDefault();e.target.click();}if(e.key==='Tab'&&!overlay.hidden){const nodes=[...overlay.querySelectorAll('button,input,select,textarea,a')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('hashchange',()=>{state.page=nav.some(n=>n[0]===location.hash.slice(1))?location.hash.slice(1):'home';closeOverlay();render();window.scrollTo(0,0);main.focus({preventScroll:true});});
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
state.page=nav.some(n=>n[0]===location.hash.slice(1))?location.hash.slice(1):'home';render();
