'use strict';
// Local-only folder and chat samples. No filesystem or messaging connections.
const folderLinks = [
  {id:1,name:'Atlas project',group:'Client Projects',path:'Nexalus shared / 1_Client projects / Atlas',note:'The project home for administration, engineering, and communications.',children:['01_Admin','02_Project_Scope','03_Engineering','05_Communications'],pinned:true},
  {id:2,name:'Orion engineering',group:'Client Projects',path:'Nexalus shared / 1_Client projects / Orion / 03_Engineering',note:'Drawings, validation, and manufacturing information.',children:['Drawings','Validation','Manufacturing'],pinned:true},
  {id:3,name:'Meridian project',group:'Client Projects',path:'Nexalus shared / 1_Client projects / Meridian',note:'Integration plans and project handover material.',children:['Planning','Engineering','Handover'],pinned:false},
  {id:4,name:'Products & drawings',group:'Internal Developments',path:'Nexalus shared / 2_Internal developments / Products',note:'Product definitions and reusable engineering information.',children:['Assemblies','CPU cold plates','GPU cold plates','Manifolds','BOMs','Drawings'],pinned:true},
  {id:5,name:'Supplier library',group:'Internal Developments',path:'Nexalus shared / 2_Internal developments / Suppliers',note:'Supplier capabilities, reference files, and meeting notes.',children:['Capabilities','Reference files','Meeting notes'],pinned:false},
  {id:6,name:'Weekly meeting notes',group:'Agendas & Meeting Notes',path:'Nexalus shared / Agendas / Weekly planning',note:'Agendas and decisions from weekly planning.',children:['September 2026','August 2026'],pinned:true},
  {id:7,name:'Company templates',group:'Templates',path:'Nexalus shared / 2_Internal developments / Templates',note:'A consistent starting point for project documentation.',children:['Project briefs','Reports','Meeting agendas'],pinned:false},
  {id:8,name:'Brand & presentations',group:'Marketing',path:'Nexalus shared / 3_Marketing / Generic_Content',note:'Shared presentation and brand material.',children:['Presentations','Brand assets','Product images'],pinned:false},
];
const conversations = [
  {id:'general',name:'general',kind:'channel',description:'Company updates and everyday questions.',members:'4 members',unread:0,messages:[{id:1,author:'Aoife Collins',initials:'AC',time:'09:05',text:'Morning all. Next week’s capacity plan is ready for a final check. Please flag any changes before Monday.',replies:[]},{id:2,author:'James Kelly',initials:'JK',time:'09:12',text:'Thanks Aoife. I’ll confirm the Orion machining slot after the drawing review.',replies:[]}]},
  {id:'atlas',name:'project-atlas',kind:'channel',description:'Cold plate validation, engineering decisions, and delivery.',members:'3 members',unread:2,project:1,folder:1,messages:[{id:1,author:'Sarah Murphy',initials:'SM',time:'10:42',text:'The latest Atlas validation summary is ready. Both test points are within the agreed envelope. I’ve highlighted two items for Monday’s review.',attachment:'Atlas_validation_summary.pdf',replies:[{author:'James Kelly',initials:'JK',time:'10:46',text:'Thanks Sarah. The manufacturing notes are ready for the same review.'}]},{id:2,author:'Sarah Murphy',initials:'SM',time:'10:48',text:'Richard, could you take a look when you have a moment? The project folder has the supporting results.',replies:[]}]},
  {id:'orion',name:'project-orion',kind:'channel',description:'Manifold assembly and manufacturing coordination.',members:'3 members',unread:1,project:2,folder:2,messages:[{id:1,author:'James Kelly',initials:'JK',time:'09:18',text:'The supplier has offered two alternative machining slots. Drawing approval is the next step before we can confirm the release date.',replies:[]}]},
  {id:'operations',name:'operations',kind:'channel',description:'Equipment, logistics, and weekly planning.',members:'4 members',unread:0,messages:[{id:1,author:'Aoife Collins',initials:'AC',time:'Yesterday',text:'The lab equipment register is up to date. Please check the calibration dates before booking the next validation run.',replies:[]}]},
  {id:'sarah',name:'Sarah Murphy',kind:'dm',description:'Engineering · Available',members:'Direct conversation',unread:1,messages:[{id:1,author:'Sarah Murphy',initials:'SM',time:'10:50',text:'Hi Richard. I’m around if you want to walk through the Atlas results before Monday.',replies:[]}]},
  {id:'james',name:'James Kelly',kind:'dm',description:'Project delivery · Available',members:'Direct conversation',unread:0,messages:[{id:1,author:'James Kelly',initials:'JK',time:'09:25',text:'I’ve added the supplier options to the Orion folder. Let me know if you need any more detail.',replies:[]}]},
  {id:'aoife',name:'Aoife Collins',kind:'dm',description:'Operations · Away',members:'Direct conversation',unread:0,messages:[{id:1,author:'Aoife Collins',initials:'AC',time:'Yesterday',text:'The capacity review is in for Monday at 14:00. We can look at the integration timing then.',replies:[]}]},
];
const workspaceState={folderFilter:'All links',folderQuery:'',recent:[4,1],conversation:'atlas',drafts:{},replyDrafts:{},thread:null};
function hubQuickAccess(){return `<div class="hub-connect"><a href="#folders">${icon('folders')}<div><b>Your folder links</b><small>${folderLinks.filter(f=>f.pinned).length} pinned shortcuts · Project files and shared resources</small></div>${icon('arrow')}</a><a href="#messages">${icon('messages')}<div><b>Stay close to your team</b><small>Channels and direct messages · ${conversations.reduce((n,c)=>n+c.unread,0)} unread sample messages</small></div>${icon('arrow')}</a></div>`;}
function folderRow(f){return `<div class="folder-row"><button class="folder-open" data-action="folder-detail" data-id="${f.id}">${icon('folders')}<span><b>${esc(f.name)}</b><small>${esc(f.path)}</small></span></button><button class="pin-button ${f.pinned?'pinned':''}" data-action="pin-folder" data-id="${f.id}" aria-label="${f.pinned?'Unpin':'Pin'} ${esc(f.name)}" aria-pressed="${f.pinned}">${f.pinned?'★':'☆'}</button></div>`;}
function folderPage(){let list=folderLinks.filter(f=>(workspaceState.folderFilter!=='Pinned'||f.pinned)&&(workspaceState.folderFilter!=='Recent'||workspaceState.recent.includes(f.id))&&`${f.name} ${f.path} ${f.group}`.toLowerCase().includes(workspaceState.folderQuery.toLowerCase()));if(workspaceState.folderFilter==='Recent')list.sort((a,b)=>workspaceState.recent.indexOf(a.id)-workspaceState.recent.indexOf(b.id));return heading('YOUR FAMILIAR SHORTCUTS','Folder Links','Project folders, shared resources, and the places you return to every day.',button('Add folder link','add-folder','',true,'plus'))+`<div class="toolbar">${tabs(['All links','Pinned','Recent'],workspaceState.folderFilter,'folders')}<input class="input" id="folder-search" aria-label="Search folder links" placeholder="Find a folder or path…" value="${esc(workspaceState.folderQuery)}"></div><div class="folder-context">${icon('folders')}<span><b>Nexalus structured folder</b><small>Grouped shortcuts inspired by your original launcher · Sample paths</small></span><span class="pill blue">${folderLinks.length} links</span></div><div class="folder-groups">${(workspaceState.folderFilter==='Recent'?['Recently previewed']:[...new Set(list.map(f=>f.group))]).map(group=>panel(group,list.filter(f=>group==='Recently previewed'||f.group===group).map(folderRow).join(''))).join('')||'<p class="empty">No folder links match this view.</p>'}</div><p class="prototype-caption">Preview a folder, pin a favourite, or add your own sample shortcut. No filesystem is connected.</p>`;}
function folderDetail(id){const f=folderLinks.find(f=>f.id===id);workspaceState.recent=[id,...workspaceState.recent.filter(x=>x!==id)].slice(0,8);showOverlay(`<span class="app-icon">${icon('folders')}</span><h2>${esc(f.name)}</h2>${pill(f.group)}<p>${esc(f.note)}</p><label>Linked location</label><div class="folder-path">${esc(f.path)}</div><div class="detail-section"><h3>Folder preview</h3>${f.children.length?f.children.map(name=>`<div class="sample-subfolder">${icon('folders')} ${esc(name)} <small>Sample subfolder</small></div>`).join(''):'<p>Your shortcut is ready. Folder contents would appear here once connected.</p>'}</div>${button(f.pinned?'Unpin shortcut':'Pin shortcut','pin-folder-detail',f.id,true)}<p class="prototype-caption">In the connected Hub this shortcut would open its folder in Explorer. This preview does not open or read local files.</p>`);}
function messageMarkup(m,thread=false){return `<article class="chat-message"><span class="avatar">${esc(m.initials)}</span><div><div class="chat-author"><b>${esc(m.author)}</b><time>${esc(m.time)}</time>${m.author==='Richard'?'<span class="pill blue">Local preview</span>':''}</div><p>${esc(m.text)}</p>${m.attachment?`<button class="attachment" data-action="chat-attachment">${icon('file')} ${esc(m.attachment)}</button>`:''}${thread?'':`<button class="link-button" data-action="chat-thread" data-id="${m.id}">${m.replies.length?`${m.replies.length} ${m.replies.length===1?'reply':'replies'}`:'Reply in thread'}</button>`}</div></article>`;}
function messagesPage(){const c=conversations.find(c=>c.id===workspaceState.conversation);return heading('TEAM CONVERSATIONS','Messages','A quick question, a project decision, or a conversation with the people you need.',button('New message','new-message','',true,'plus'))+`<section class="panel chat-layout"><aside class="chat-nav" aria-label="Conversations"><div class="chat-workspace"><b>Nexalus team</b><small><span class="presence"></span> Sample workspace · 4 people</small></div>${['channel','dm'].map(kind=>`<p class="chat-nav-label">${kind==='channel'?'CHANNELS':'DIRECT MESSAGES'}</p>${conversations.filter(x=>x.kind===kind).map(x=>`<button class="conversation ${c.id===x.id?'active':''}" data-action="conversation" data-id="${x.id}" aria-pressed="${c.id===x.id}"><span>${kind==='channel'?'#':`<i class="presence ${x.id==='aoife'?'away':''}"></i>`}</span>${esc(x.name)}${x.unread?`<b class="unread">${x.unread}</b>`:''}</button>`).join('')}`).join('')}<p class="chat-presence-note">Presence is illustrative.</p></aside><div class="chat-room"><div class="chat-room-header"><div><h2>${c.kind==='channel'?'# ':''}${esc(c.name)}</h2><small>${esc(c.description)}</small></div>${button(c.kind==='channel'?c.members:'View person','chat-people',c.id)}</div>${c.project?`<div class="chat-context">${icon('projects')}<span>Shared project context</span>${link('Project','project',c.project)}${link('Folder','folder-detail',c.folder)}</div>`:''}<div class="chat-log" aria-label="Conversation history"><div class="chat-date">Saturday, 12 September</div>${c.messages.map(m=>messageMarkup(m)).join('')}</div><form id="chat-compose" class="chat-compose"><label for="chat-draft">Message ${c.kind==='channel'?'#':''}${esc(c.name)}</label><textarea id="chat-draft" rows="3" maxlength="4000" placeholder="Write a message…">${esc(workspaceState.drafts[c.id]||'')}</textarea><div><small>Preview only · Visible to you · Ctrl+Enter to post</small><button type="submit" class="button primary">Post in preview ${icon('arrow')}</button></div></form></div></section>`;}
function openConversation(id){workspaceState.conversation=id;conversations.find(c=>c.id===id).unread=0;go('messages');}
function chatThread(id){const c=conversations.find(c=>c.id===workspaceState.conversation),m=c.messages.find(m=>m.id===id);workspaceState.thread=id;const key=`${c.id}:${id}`;showOverlay(`<h2>Thread</h2><small>${c.kind==='channel'?'# ':''}${esc(c.name)}</small>${messageMarkup(m,true)}<div class="thread-replies">${m.replies.map(r=>messageMarkup(r,true)).join('')||'<p>Start a focused reply to this message.</p>'}</div><form id="thread-compose" class="chat-compose"><label for="reply-draft">Reply in thread</label><textarea id="reply-draft" rows="3" maxlength="4000" placeholder="Write a reply…">${esc(workspaceState.replyDrafts[key]||'')}</textarea><button class="button primary" type="submit">Post reply in preview</button></form><p class="prototype-caption">Replies stay in this browser session. Nothing is sent to your team.</p>`);}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const id=Number(el.dataset.id);switch(el.dataset.action){
  case 'filter':if(el.dataset.type==='folders'){workspaceState.folderFilter=el.dataset.id;render();}break;
  case 'folder-detail':folderDetail(id);break;
  case 'pin-folder':folderLinks.find(f=>f.id===id).pinned=!folderLinks.find(f=>f.id===id).pinned;render();break;
  case 'pin-folder-detail':folderLinks.find(f=>f.id===id).pinned=!folderLinks.find(f=>f.id===id).pinned;render();folderDetail(id);break;
  case 'add-folder':showOverlay(`<h2>Add folder link</h2><p>Keep a useful location close by, just like in the original launcher.</p><form id="folder-form"><label for="folder-name">Shortcut name</label><input class="input" id="folder-name" required maxlength="80" placeholder="e.g. Test reports"><label for="folder-location">Folder path</label><input class="input" id="folder-location" required maxlength="500" placeholder="e.g. N:\\Projects\\Atlas\\Test reports"><label for="folder-group">Group</label><select class="input" id="folder-group">${['Client Projects','Internal Developments','Marketing','Agendas & Meeting Notes','Templates','Other'].map(g=>`<option>${g}</option>`).join('')}</select><button type="submit" class="button primary">Save preview link</button></form><p class="prototype-caption">Saves a shortcut in memory only. It does not check or access the path.</p>`);break;
  case 'conversation':openConversation(el.dataset.id);break;
  case 'new-message':showOverlay(`<h2>Start a conversation</h2><p>Find a colleague and continue in a direct message.</p>${conversations.filter(c=>c.kind==='dm').map(c=>`<button class="person-picker" data-action="conversation" data-id="${c.id}"><span class="avatar">${c.name.split(' ').map(x=>x[0]).join('')}</span><span><b>${c.name}</b><small>${c.description}</small></span>${icon('arrow')}</button>`).join('')}<p class="prototype-caption">Sample people and conversations only.</p>`);break;
  case 'chat-thread':chatThread(id);break;
  case 'chat-people':{const c=conversations.find(c=>c.id===el.dataset.id);const people=c.kind==='dm'?conversations.filter(p=>p.id===c.id):conversations.filter(p=>p.kind==='dm'&&(['general','operations'].includes(c.id)||p.id!=='aoife'));showOverlay(`<h2>${c.kind==='dm'?'Contact':'Channel members'}</h2><p>${esc(c.name)}</p><div class="person-picker"><span class="avatar">RM</span><span><b>Richard</b><small>You · Administrator</small></span></div>${people.map(p=>`<button class="person-picker" data-action="conversation" data-id="${p.id}"><span class="avatar">${p.name.split(' ').map(x=>x[0]).join('')}</span><span><b>${p.name}</b><small>${p.description}</small></span>${icon('messages')}</button>`).join('')}<p class="prototype-caption">Select a person to open their sample conversation.</p>`);break;}
  case 'chat-attachment':showOverlay(`${icon('file')}<h2>Atlas validation summary</h2><p>Two thermal test points are within the agreed performance envelope. Two items remain for the engineering review.</p>${button('View project folder','folder-detail',1,true)}<p class="prototype-caption">Illustrative attachment summary. No file is downloaded.</p>`);break;
}});
document.addEventListener('input',e=>{if(e.target.id==='folder-search'){const caret=e.target.selectionStart;workspaceState.folderQuery=e.target.value;render();const input=document.querySelector('#folder-search');input.focus();input.setSelectionRange(caret,caret);}if(e.target.id==='chat-draft')workspaceState.drafts[workspaceState.conversation]=e.target.value;if(e.target.id==='reply-draft')workspaceState.replyDrafts[`${workspaceState.conversation}:${workspaceState.thread}`]=e.target.value;});
document.addEventListener('submit',e=>{if(e.target.id==='folder-form'){e.preventDefault();const name=document.querySelector('#folder-name').value.trim(),path=document.querySelector('#folder-location').value.trim();if(!name||!path){showToast('Enter a shortcut name and folder path.');return;}folderLinks.push({id:Math.max(...folderLinks.map(f=>f.id))+1,name,path,group:document.querySelector('#folder-group').value,note:'Your sample folder shortcut.',children:[],pinned:true});workspaceState.folderFilter='All links';workspaceState.folderQuery='';closeOverlay();render();showToast('Folder link added and pinned in preview.');}if(e.target.id==='chat-compose'||e.target.id==='thread-compose'){e.preventDefault();const reply=e.target.id==='thread-compose',input=document.querySelector(reply?'#reply-draft':'#chat-draft'),text=input.value.trim();if(!text){input.focus();return;}const c=conversations.find(c=>c.id===workspaceState.conversation),entry={author:'Richard',initials:'RM',time:'Just now',text};if(reply){c.messages.find(m=>m.id===workspaceState.thread).replies.push(entry);workspaceState.replyDrafts[`${c.id}:${workspaceState.thread}`]='';render();chatThread(workspaceState.thread);}else{c.messages.push({...entry,id:Math.max(0,...c.messages.map(m=>m.id))+1,replies:[]});workspaceState.drafts[c.id]='';render();document.querySelector('#chat-draft').focus();document.querySelector('.chat-log').scrollTop=1e6;}showToast('Posted locally in preview. Nothing was sent.');}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&['chat-draft','reply-draft'].includes(e.target.id)){e.preventDefault();e.target.closest('form').requestSubmit();}});
